const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

const books = [
  {
    id: 1,
    title: "Foundation",
    author: "Isaac Asimov",
    price: 22,
    discountPrice: 10,
    category: "Romance",
    rating: 4.1,
    reviewCount: 452,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/14612610-L.jpg",
    stock: 24,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "spa",
    isbn: "N/A",
    format: "digital",
    isFeatured: true,
    samplePdf: "#",
  },
  {
    id: 2,
    title: "Ficciones",
    author: "Jorge Luis Borges",
    price: 28,
    discountPrice: 9,
    category: "Romance",
    rating: 4.4,
    reviewCount: 148,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/10832290-L.jpg",
    stock: 41,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "spa",
    isbn: "N/A",
    format: "physical",
    isFeatured: true,
    samplePdf: "#",
  },
  {
    id: 3,
    title: "Dracula",
    author: "Bram Stoker",
    price: 27,
    discountPrice: 8,
    category: "Romance",
    rating: 4.8,
    reviewCount: 64,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/12216503-L.jpg",
    stock: 28,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "eng",
    isbn: "N/A",
    format: "physical",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 4,
    title: "The Mysterious Affair at Styles",
    author: "Agatha Christie",
    price: 12,
    discountPrice: 10,
    category: "Romance",
    rating: 4.6,
    reviewCount: 287,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/13699667-L.jpg",
    stock: 44,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "heb",
    isbn: "N/A",
    format: "digital",
    isFeatured: true,
    samplePdf: "#",
  },
  {
    id: 5,
    title: "Beloved",
    author: "Toni Morrison",
    price: 11,
    discountPrice: 12,
    category: "Romance",
    rating: 3.5,
    reviewCount: 19,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/8261367-L.jpg",
    stock: 44,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "ger",
    isbn: "N/A",
    format: "digital",
    isFeatured: true,
    samplePdf: "#",
  },
  {
    id: 6,
    title: "The Last Man",
    author: "Mary Shelley",
    price: 27,
    discountPrice: 11,
    category: "Romance",
    rating: 3.0,
    reviewCount: 122,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/882662-L.jpg",
    stock: 27,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "ita",
    isbn: "N/A",
    format: "physical",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 7,
    title: "The Time Machine",
    author: "H. G. Wells",
    price: 17,
    discountPrice: 11,
    category: "Romance",
    rating: 3.8,
    reviewCount: 260,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/9009316-L.jpg",
    stock: 47,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "tam",
    isbn: "N/A",
    format: "physical",
    isFeatured: true,
    samplePdf: "#",
  },
  {
    id: 8,
    title: "Herland",
    author: "Charlotte Perkins Gilman",
    price: 22,
    discountPrice: 9,
    category: "Romance",
    rating: 3.8,
    reviewCount: 272,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/448130-L.jpg",
    stock: 7,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "ger",
    isbn: "N/A",
    format: "digital",
    isFeatured: true,
    samplePdf: "#",
  },
  {
    id: 9,
    title: "The Invisible Man",
    author: "H. G. Wells",
    price: 13,
    discountPrice: 8,
    category: "Romance",
    rating: 3.0,
    reviewCount: 54,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/6419199-L.jpg",
    stock: 21,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "mon",
    isbn: "N/A",
    format: "physical",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 10,
    title: "Dune",
    author: "Frank Herbert",
    price: 11,
    discountPrice: 7,
    category: "Romance",
    rating: 4.2,
    reviewCount: 303,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/11481354-L.jpg",
    stock: 40,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "ger",
    isbn: "N/A",
    format: "digital",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 11,
    title: "Мы",
    author: "Евгений Иванович Замятин",
    price: 17,
    discountPrice: 7,
    category: "Science Fiction",
    rating: 3.6,
    reviewCount: 359,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/5484189-L.jpg",
    stock: 29,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "srp",
    isbn: "N/A",
    format: "physical",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 12,
    title: "A Room of One's Own",
    author: "Virginia Woolf",
    price: 14,
    discountPrice: 12,
    category: "Science Fiction",
    rating: 3.4,
    reviewCount: 318,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/6559057-L.jpg",
    stock: 24,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "dan",
    isbn: "N/A",
    format: "physical",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 13,
    title: "The Yellow Wallpaper",
    author: "Charlotte Perkins Gilman",
    price: 14,
    discountPrice: 9,
    category: "Science Fiction",
    rating: 3.2,
    reviewCount: 204,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/652029-L.jpg",
    stock: 6,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "eng",
    isbn: "N/A",
    format: "physical",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 14,
    title: "The War of the Worlds",
    author: "H. G. Wells",
    price: 23,
    discountPrice: 10,
    category: "Science Fiction",
    rating: 4.1,
    reviewCount: 491,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/36314-L.jpg",
    stock: 48,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "fre",
    isbn: "N/A",
    format: "physical",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 15,
    title: "Dubliners",
    author: "James Joyce",
    price: 13,
    discountPrice: 12,
    category: "Science Fiction",
    rating: 4.6,
    reviewCount: 129,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/8216412-L.jpg",
    stock: 46,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "heb",
    isbn: "N/A",
    format: "physical",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 16,
    title: "Kim",
    author: "Rudyard Kipling",
    price: 19,
    discountPrice: 12,
    category: "Science Fiction",
    rating: 4.1,
    reviewCount: 137,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/1053011-L.jpg",
    stock: 15,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "pol",
    isbn: "N/A",
    format: "physical",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 17,
    title: "The Riddle of the Sands",
    author: "Erskine Childers",
    price: 15,
    discountPrice: 13,
    category: "Science Fiction",
    rating: 3.9,
    reviewCount: 144,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/2293974-L.jpg",
    stock: 29,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "eng",
    isbn: "N/A",
    format: "digital",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 18,
    title: "The blue castle",
    author: "Lucy Maud Montgomery",
    price: 23,
    discountPrice: 11,
    category: "Science Fiction",
    rating: 4.0,
    reviewCount: 420,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/14640067-L.jpg",
    stock: 33,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "chi",
    isbn: "N/A",
    format: "digital",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 19,
    title: "The Scarlet Pimpernel",
    author: "Emma Orczy",
    price: 29,
    discountPrice: 7,
    category: "Science Fiction",
    rating: 4.9,
    reviewCount: 205,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/479102-L.jpg",
    stock: 46,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "eng",
    isbn: "N/A",
    format: "physical",
    isFeatured: true,
    samplePdf: "#",
  },
  {
    id: 20,
    title: "Lord Jim",
    author: "Joseph Conrad",
    price: 28,
    discountPrice: 7,
    category: "Science Fiction",
    rating: 3.1,
    reviewCount: 383,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/8236295-L.jpg",
    stock: 22,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "spa",
    isbn: "N/A",
    format: "digital",
    isFeatured: true,
    samplePdf: "#",
  },
  {
    id: 21,
    title: "The Awakening",
    author: "Kate Chopin",
    price: 10,
    discountPrice: 11,
    category: "Fantasy",
    rating: 3.4,
    reviewCount: 469,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/8750241-L.jpg",
    stock: 24,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "cat",
    isbn: "N/A",
    format: "digital",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 22,
    title: "The Martian Chronicles",
    author: "Ray Bradbury",
    price: 16,
    discountPrice: 7,
    category: "Fantasy",
    rating: 4.0,
    reviewCount: 365,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/9346537-L.jpg",
    stock: 51,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "eng",
    isbn: "N/A",
    format: "physical",
    isFeatured: true,
    samplePdf: "#",
  },
  {
    id: 23,
    title: "Shirley",
    author: "Charlotte Brontë",
    price: 14,
    discountPrice: 10,
    category: "Fantasy",
    rating: 3.4,
    reviewCount: 418,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/11024634-L.jpg",
    stock: 52,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "ger",
    isbn: "N/A",
    format: "physical",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 24,
    title: "Of Human Bondage",
    author: "William Somerset Maugham",
    price: 10,
    discountPrice: 6,
    category: "Fantasy",
    rating: 3.1,
    reviewCount: 4,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/5277723-L.jpg",
    stock: 31,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "vie",
    isbn: "N/A",
    format: "physical",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 25,
    title: "Flatland",
    author: "Edwin Abbott Abbott",
    price: 17,
    discountPrice: 7,
    category: "Fantasy",
    rating: 4.4,
    reviewCount: 365,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/10069547-L.jpg",
    stock: 35,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "epo",
    isbn: "N/A",
    format: "physical",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 26,
    title: "Ethan Frome",
    author: "Edith Wharton",
    price: 15,
    discountPrice: 5,
    category: "Fantasy",
    rating: 3.7,
    reviewCount: 384,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/8303480-L.jpg",
    stock: 9,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "ger",
    isbn: "N/A",
    format: "physical",
    isFeatured: true,
    samplePdf: "#",
  },
  {
    id: 27,
    title: "Persuasion",
    author: "Jane Austen",
    price: 13,
    discountPrice: 5,
    category: "Fantasy",
    rating: 4.5,
    reviewCount: 219,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/12824691-L.jpg",
    stock: 51,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "eng",
    isbn: "N/A",
    format: "digital",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 28,
    title: "The Sign of Four",
    author: "Arthur Conan Doyle",
    price: 19,
    discountPrice: 12,
    category: "Fantasy",
    rating: 3.6,
    reviewCount: 354,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/9247987-L.jpg",
    stock: 49,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "cat",
    isbn: "N/A",
    format: "digital",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 29,
    title: "Le roman du masque de fer",
    author: "Alexandre Dumas",
    price: 26,
    discountPrice: 14,
    category: "Fantasy",
    rating: 4.6,
    reviewCount: 121,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/2132494-L.jpg",
    stock: 11,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "eng",
    isbn: "N/A",
    format: "digital",
    isFeatured: true,
    samplePdf: "#",
  },
  {
    id: 30,
    title: "This Side of Paradise",
    author: "F. Scott Fitzgerald",
    price: 19,
    discountPrice: 10,
    category: "Fantasy",
    rating: 4.5,
    reviewCount: 88,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/8243609-L.jpg",
    stock: 46,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "eng",
    isbn: "N/A",
    format: "physical",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 31,
    title: "The Adventures of Tom Sawyer",
    author: "Mark Twain",
    price: 16,
    discountPrice: 9,
    category: "Mystery",
    rating: 4.5,
    reviewCount: 67,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/12043351-L.jpg",
    stock: 27,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "fre",
    isbn: "N/A",
    format: "digital",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 32,
    title: "The Great God Pan",
    author: "Arthur Machen",
    price: 28,
    discountPrice: 8,
    category: "Mystery",
    rating: 4.3,
    reviewCount: 356,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/921610-L.jpg",
    stock: 18,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "dut",
    isbn: "N/A",
    format: "physical",
    isFeatured: true,
    samplePdf: "#",
  },
  {
    id: 33,
    title: "The Sea Fairies",
    author: "L. Frank Baum",
    price: 12,
    discountPrice: 10,
    category: "Mystery",
    rating: 4.3,
    reviewCount: 384,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/1814237-L.jpg",
    stock: 42,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "rus",
    isbn: "N/A",
    format: "physical",
    isFeatured: true,
    samplePdf: "#",
  },
  {
    id: 34,
    title: "The First Men in the Moon",
    author: "H. G. Wells",
    price: 26,
    discountPrice: 11,
    category: "Mystery",
    rating: 5.0,
    reviewCount: 203,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/8081288-L.jpg",
    stock: 45,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "gle",
    isbn: "N/A",
    format: "physical",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 35,
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    price: 12,
    discountPrice: 5,
    category: "Mystery",
    rating: 4.4,
    reviewCount: 466,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/12993656-L.jpg",
    stock: 15,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "eng",
    isbn: "N/A",
    format: "digital",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 36,
    title: "The Lost World",
    author: "Arthur Conan Doyle",
    price: 13,
    discountPrice: 10,
    category: "Mystery",
    rating: 4.0,
    reviewCount: 479,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/8231444-L.jpg",
    stock: 53,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "cze",
    isbn: "N/A",
    format: "digital",
    isFeatured: true,
    samplePdf: "#",
  },
  {
    id: 37,
    title: "The Scarlet Letter",
    author: "Nathaniel Hawthorne",
    price: 29,
    discountPrice: 6,
    category: "Mystery",
    rating: 4.5,
    reviewCount: 334,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/5654516-L.jpg",
    stock: 9,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "pol",
    isbn: "N/A",
    format: "digital",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 38,
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    price: 10,
    discountPrice: 9,
    category: "Mystery",
    rating: 4.1,
    reviewCount: 364,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/14314858-L.jpg",
    stock: 17,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "eng",
    isbn: "N/A",
    format: "physical",
    isFeatured: true,
    samplePdf: "#",
  },
  {
    id: 39,
    title: "Sons and Lovers",
    author: "D. H. Lawrence",
    price: 15,
    discountPrice: 6,
    category: "Mystery",
    rating: 4.0,
    reviewCount: 34,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/8246175-L.jpg",
    stock: 13,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "spa",
    isbn: "N/A",
    format: "digital",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 40,
    title: "Lilith",
    author: "George MacDonald",
    price: 24,
    discountPrice: 7,
    category: "Mystery",
    rating: 4.2,
    reviewCount: 473,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/14364546-L.jpg",
    stock: 46,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "ita",
    isbn: "N/A",
    format: "digital",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 41,
    title: "Wuthering Heights",
    author: "Emily Brontë",
    price: 21,
    discountPrice: 10,
    category: "Fiction",
    rating: 3.9,
    reviewCount: 139,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/12818862-L.jpg",
    stock: 17,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "eng",
    isbn: "N/A",
    format: "physical",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 42,
    title: "The Adventures of Sherlock Holmes [12 stories]",
    author: "Arthur Conan Doyle",
    price: 17,
    discountPrice: 7,
    category: "Fiction",
    rating: 4.1,
    reviewCount: 496,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/6717853-L.jpg",
    stock: 8,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "pol",
    isbn: "N/A",
    format: "digital",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 43,
    title: "The Book of Dragons",
    author: "Edith Nesbit",
    price: 11,
    discountPrice: 14,
    category: "Fiction",
    rating: 4.0,
    reviewCount: 182,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/4342323-L.jpg",
    stock: 9,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "eng",
    isbn: "N/A",
    format: "physical",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 44,
    title: "The Good Earth",
    author: "Pearl S. Buck",
    price: 11,
    discountPrice: 8,
    category: "Fiction",
    rating: 4.6,
    reviewCount: 495,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/2626823-L.jpg",
    stock: 24,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "vie",
    isbn: "N/A",
    format: "physical",
    isFeatured: true,
    samplePdf: "#",
  },
  {
    id: 45,
    title: "Sense and Sensibility",
    author: "Jane Austen",
    price: 20,
    discountPrice: 7,
    category: "Fiction",
    rating: 3.2,
    reviewCount: 481,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/9278292-L.jpg",
    stock: 6,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "pol",
    isbn: "N/A",
    format: "digital",
    isFeatured: true,
    samplePdf: "#",
  },
  {
    id: 46,
    title: "My Ántonia",
    author: "Willa Cather",
    price: 25,
    discountPrice: 8,
    category: "Fiction",
    rating: 3.5,
    reviewCount: 147,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/8369013-L.jpg",
    stock: 19,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "fre",
    isbn: "N/A",
    format: "digital",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 47,
    title: "When the Sleeper Awakes",
    author: "H. G. Wells",
    price: 28,
    discountPrice: 6,
    category: "Fiction",
    rating: 4.7,
    reviewCount: 182,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/574886-L.jpg",
    stock: 40,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "epo",
    isbn: "N/A",
    format: "physical",
    isFeatured: false,
    samplePdf: "#",
  },
  {
    id: 48,
    title: "A Tale of Two Cities",
    author: "Charles Dickens",
    price: 18,
    discountPrice: 5,
    category: "Fiction",
    rating: 3.9,
    reviewCount: 51,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/13301713-L.jpg",
    stock: 31,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "guj",
    isbn: "N/A",
    format: "digital",
    isFeatured: true,
    samplePdf: "#",
  },
  {
    id: 49,
    title: "Poetics",
    author: "Aristotle",
    price: 23,
    discountPrice: 9,
    category: "Fiction",
    rating: 3.0,
    reviewCount: 43,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/6528920-L.jpg",
    stock: 24,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "ger",
    isbn: "N/A",
    format: "digital",
    isFeatured: true,
    samplePdf: "#",
  },
  {
    id: 50,
    title: "Anthem",
    author: "Ayn Rand",
    price: 16,
    discountPrice: 7,
    category: "Fiction",
    rating: 4.4,
    reviewCount: 474,
    description: "A captivating book worth reading.",
    image: "https://covers.openlibrary.org/b/id/802982-L.jpg",
    stock: 47,
    pages: 250,
    publisher: "Unknown Publisher",
    language: "eng",
    isbn: "N/A",
    format: "physical",
    isFeatured: false,
    samplePdf: "#",
  },
];

async function main() {
  await prisma.book.createMany({
    data: books,
    skipDuplicates: true
  });

  console.log("Books seeded successfully 📚");
}

main()
  .catch((e) => {
    console.error(e);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });